#!/bin/env bash
#rsa factorial

test_factor()
{
    if [ $# -ne 3 ];
    then
	    args=("$@")
	    ctr=0
	    m2=1
	    for n in ${args[*]};
            do
		    if [ $ctr -gt 1 ];
		    then
			    m2=$(echo $n*$m2 | bc)
		    fi
		    ctr=$((ctr + 1))
	    done
    else
	    m2=$3
    fi

    m1=$2
    m=$(echo "$1" | tr ':' '=')

    res=$(echo "if($m2 > $m1) 1 else 0" | bc)
        if ((res == 1)); then
		mcp=$m1
		m1=$m2
		m2=$mcp
	fi
    echo "$m$m1*$m2"
}

if [ $# -ne 1 ]
then
	echo 'Usage: rsa <file>'
	exit 1
else
	while read i
	do
		res=$(factor "$i")
		test_factor $res
	done < "$1"
fi
